### PR TITLE
[WIP] Prettier require resolution

### LINKED ISSUE #29: Use prettier from current workspace
Currently plugin uses internal dependency on prettier. I think it would be better to use prettier from current projects node_modules, if it exists.

### PR DESCRIPTION
**Pull request by CiGit**
Will resolve prettier in the following order
 1. local resolution
 1. ~~global resolution~~ *postponed*
 1. package resolution

Progress:
- [x]  require local 
- [x] require packaged

Other:
- [x] Changelog
- [ ] Readme

fixes #29 

~~Currently I'm waiting for a [response](https://github.com/esbenp/prettier-vscode/issues/29#issuecomment-280619152) on how to implement global resolution.~~ *global resolution postponed*

### CODE REVIEW

**Comment by CiGit** [comment]
@esbenp What do you think about making an other PR with global resolution once *how* as been defined. Use this PR only for it's local resolution.

By local I mean resolve relatively to the file being processed. Not a _workspace_ resolution.

**Comment by esbenp** [comment]
Yes I think we should just get this one out there. Ignore the global thing for now.

**Comment by CiGit** [comment]
:+1: will update that in next hours.

**Comment by CiGit** [comment]
I've not touched the Readme. I don't know if I should put something in it about those change.

Review please.

**Comment by esbenp** [comment]
Released in `0.11.0` https://github.com/esbenp/prettier-vscode/releases/tag/0.11.0

**Comment by yannuil** [comment]
Any plans on the global resolutions?

**Comment by CiGit** [comment]
None. If this is something for you, please open a new issue.

**Pull request merged**
