### PR TITLE
Allow disabling formatting when prettier is not installed in the proj…

### PR DESCRIPTION
**Pull request by jacobp100**
Allow disabling formatting when prettier is not installed in the project to assist with editor.saveOnFormat

### CODE REVIEW

**Comment by jacobp100** [comment]
Or is the way to go about this to use workspace settings? Not sure!

**Comment by CiGit** [comment]
Without testing this I think this is also disabling the default formatter but I may be wrong.
Wouldn't it be easier to disable the extension for the current workspace?

**Comment by jacobp100** [comment]
Yea, tbh I only realised you could do per-project settings after I coded this and was testing 😂 Fool free to close if you don't think it would be useful.

**Comment by frederickfogerty** [comment]
I think this is still useful, as I might want to use another formatter, and just disable prettier. Using `editor.formatOnSave` disables all formatters.

**Comment by CiGit** [comment]
I did not mean to disable `formatOnSave` but disable the extension for the workspace

**Comment by frederickfogerty** [comment]
Oh, @CiGit how do you do that?

**Comment by CiGit** [comment]
There is a cogwheel for each extension in the extensions pane.

**Pull request closed without merging**
