### PR TITLE
Override the package name which is used to search in local dependencies

### PR DESCRIPTION
**Pull request by Alphapage**
Related to https://github.com/esbenp/prettier-vscode/issues/164

### CODE REVIEW

**Comment by CiGit** [comment]
I'm not that convinced we want such an option. I think this will cause more troubles than bringing solutions.

**Comment by Alphapage** [comment]
No problem. It was just a helper for my particular problem.

**Comment by CiGit** [comment]
You may want to maintain a fork for your *particular problem*.
This seems to create a conflict between eslintIntegration and this option ;-) prettier-eslint will still search for a *prettier* package.

**Comment by Alphapage** [comment]
Yes, this will probably cause problems for prettier dependent packages, even if prettier-eslint has an option to set prettierPath.

**Comment by bySabi** [comment]
@Alphapage I wrote a script that fork `prettier-vscode`, patch, create VSIX and publish.
Maybe can be useful to you:

https://github.com/bySabi/patch--prettier-vscode

**Comment by Alphapage** [comment]
Interesting. I will investigate this option. Thank you.

**Pull request closed without merging**
