### PR TITLE
Added prettier dark icon.

### LINKED ISSUE #86: missing an extension icon
it would be nice if this package could have an image in extension marketplace

### PR DESCRIPTION
**Pull request by tomphilbin**
Added the prettier dark icon from https://github.com/ianstormtaylor/prettier-logo as it looks like these designs will be adopted based on the version 1 announcement (http://jlongster.com/prettier-1.0) and community discussion (https://github.com/prettier/prettier/issues/757). 

This is how it looks in the extensions sidebar:

screen shot 2017-04-21 at 17 49 17

EDIT @cigit: Fixes #86

### CODE REVIEW

**Comment by CiGit** [comment]
Great! 
I've also seen 2 variations on the logo. Seems we agree on which will be the *official* one.

But I'm not sure we can use it.
The repository where you have taken it from has no license.

**Comment by tomphilbin** [comment]
Ah, I missed that! 

Opened an issue (https://github.com/ianstormtaylor/prettier-logo/issues/2) and will update here once it's been added.

**Comment by CiGit** [comment]
Can you also put a screenshot with the light theme ?

**Comment by tomphilbin** [comment]
Sure, it looks like this: 

screen shot 2017-04-22 at 13 15 46

Which do you prefer?

**Comment by CiGit** [comment]
Sorry I meant vscode with a light theme not the icon.

Between both I prefer the dark icon.

**Comment by tomphilbin** [comment]
Oops, sorry! Here you go:

screen shot 2017-04-22 at 13 41 29

**Comment by CiGit** [comment]
The background isn't transparent?
https://github.com/ianstormtaylor/prettier-logo/blob/master/images/prettier-icon-dark.png

**Comment by tomphilbin** [comment]
Oh, I took the dark avatar one and cropped it (https://github.com/ianstormtaylor/prettier-logo/blob/master/images/prettier-avatar-dark.

Updated the branch, this is how they look now.

screen shot 2017-04-22 at 14 33 00
screen shot 2017-04-22 at 14 33 33

**Comment by CiGit** [comment]
Looks good to me.
I think @esbenp should approve this choice.
And missing license.

**Comment by will-stone** [comment]
Prettier is now using the icon, and Prettier is MIT licensed, I reckon that means you're good to go.

**Comment by CiGit** [comment]
I'm sorry, I've done it with prettier's icon. One from prettier/prettier (MIT, official) https://github.com/prettier/prettier/blob/eccb17495aeb413c1c19644bbb4a17d294012dfd/docs/icon.png

**Comment by tomphilbin** [comment]
I would have been happy to do this. You should give your contributors a chance to complete their PRs before doing it yourself in the future.

**Comment by CiGit** [comment]
You are right. Was a little too enthusiastic after having found a *workaround*.
I'll force push master without my changes !

**Comment by CiGit** [comment]
Done :-)
Sorry for those who would have taken HEAD in the meantime!

**Comment by CiGit** [comment]
So. Could you please update the image to https://github.com/prettier/prettier/blob/eccb17495aeb413c1c19644bbb4a17d294012dfd/docs/icon.png
And resize it to 128x128 (50%).
I don't think we should make it transparent. It doesn't feel great on white background. (And it's official)

**Comment by tomphilbin** [comment]
Awesome, thanks a lot for doing that. I've updated with the requested image :)

**Comment by CiGit** [comment]
Thanks!

**Pull request merged**
