### PR TITLE
update prettier to 0.19.0

### PR DESCRIPTION
**Pull request by dburles**
until #29 is answered the best solution is to keep the dependency up to date

### CODE REVIEW

**Comment by CiGit** [comment]
Thanks, could you also update `trailingComma` ? Option changed in 0.19.0 from a boolean value to string value in `['none', 'es5', 'all']` https://github.com/prettier/prettier/blob/master/CHANGELOG.md#0190

**Comment by dburles** [comment]
Sure thing

**Comment by CiGit** [comment]
Forgot to point you relevant parts.
Source files which change can be found as an example in #38.

**Comment by dburles** [comment]
Thanks, would you mind pointing me in the direction of how to test the extension locally? first time working on a vscode extension.

**Comment by CiGit** [comment]
Sure.
We have no automated tests. Maybe one day...
You can run the extension `F5` and then in the new window open a JS project to play with. You can also put breakpoints to have a *chrome like* debugger.

**Comment by CiGit** [comment]
@dburles I've just done this, hope you won't mind if you were doing it #38

**Comment by dburles** [comment]
I haven't had a chance to work on it yet so that's great!

**Pull request closed without merging**
